            - name: Build & Publish Debug APK
  # You may pin to the exact commit or the version.
  # uses: ShaunLWM/action-release-debugapk@d804d8fbf2982783eeffb6fa9e12bf37beb519bd
  uses: ShaunLWM/action-release-debugapk@0.0.7
  with:
    # Github secret token to allow automated publishing of APK to release.
    GITHUB_TOKEN: 
    # Github repository branch name.
    REPO_BRANCH: # optional
          
